### PR TITLE
Make configurable through environment variable

### PR DESCRIPTION
**Pull request by wnagele**
This change enables the addition of configuration directives through the TOR_CONFIG environment variable.

### CODE REVIEW

**Comment by wnagele** [comment]
Did you want to merge this?

**Comment by UserTaken** [comment]
I think if you want a more complex config, you could just bind mount one in instead of using extremely long runtime environmental variable.

**Comment by wnagele** [comment]
Plenty of options for sure - most Docker related tools seem to go down the path of allowing environment variables for such tasks. Thus this is likely the most useful to users.

**Comment by UserTaken** [comment]
I changed `tor` to be the entrypoint instead so now you can pass any config options after that.

```
docker run -d --restart always --name tor-proxy -p 9050:9050 usertaken/tor-socks-proxy ExitNodes {us}
```

**Comment by wnagele** [comment]
Ok - closing this pull request. Thanks for the change!

**Pull request closed without merging**
